#!/bin/sh

compiler_prefix=""
usage="Build helper:
Usage: construct [action] [options]

Actions:
    build | b
    run | r                    Run with QEMU
Options:
    -c [compiler prefix]       Compiler prefix to use. Make sure it is in PATH. 
                               Leave empty for system default. e.x. aarch-elf
"

colour_print () {
    printf "[33m%s[0m\n" "$1"
}

build () {
    # Default cflags
    cflags="-Wall -Wextra -ffreestanding -MD"
    ninja_file=$(printf "cflags = %s" "$cflags")

    # Includes
    colour_print "Generating Includes"
    ninja_file+=$(printf "\nincludes =")
    includes=$(find src/ -name "include" -type d)
    for inc in $includes; do
        ninja_file+=$(printf " -I%s" "$inc")
    done

    colour_print "Generating Sources"
    # Rules
    ninja_file+=$(printf "\n\nrule cc") 
    ninja_file+=$(printf "\n    command = %sgcc \$cflags \$includes -c \$in -o \$out" "$compiler_prefix")
    ninja_file+=$(printf "\n\nrule link")
    ninja_file+=$(printf "\n    command = %sld -nostdlib \$in -T linker.ld -o \$out" "$compiler_prefix")

    # Generating Sources
    ninja_file+=$(printf "\n ")
    sources=$(find src/ -name "*.[Sc]")
    objects=""
    for src in $sources; do
        dest=$(printf "%s" "$src" | sed "s/\.[Sc]/\.o/" | sed "s/src/build/")
        ninja_file+=$(printf "\nbuild %s: cc %s" "$dest" "$src")
        objects+=$(printf "%s " "$dest")
    done

    # Link
    colour_print "Linking"
    ninja_file+=$(printf "\nbuild build/kernel8.elf: link %s" "$objects")

    mkdir -p build
    printf "%s\n" "$ninja_file" > build.ninja
}

while :; do
    case $1 in
        -c)
            [ -z "$2" ] && printf "Error: No compiler given\n" && exit 1
            compiler_prefix="$2-"
            shift
            ;;
        -h)
            printf "%s" "$usage"
            exit
            ;;
        build | b)
            build
            exit
            ;;
        run | r)
            qemu-system-aarch64 -M raspi3b -kernel build/kernel8.elf -serial null -serial stdio
            exit
            ;;
        --)
            shift
            break
            ;;
        *)
            printf "%s" "$usage" && exit 1
            shift
    esac
    shift
done
